import './js/header';
import './js/dark-theme';
// import './js/categories';
import './js/support';
// import './js/hero';
import './js/shopping_list/shopping';
// import './js/modal';
import './js/modalLogin';
import './js/loader';
import './js/scrollUp';
import './js/shopping_list/pagination';
